GET http://localhost:3000/users
###
GET http://localhost:3000/users/6334fe82c6e5a2afa28b0323
###
POST  http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Cooper",
    "lastName": "Kupp",
    "email": "kupp@gmail.com",
    "password": "Kupp10copper"
}
###
PUT  http://localhost:3000/users/633cea619475ad3f03ca2091
Content-Type: application/json

{
    "firstName": "Troy",
    "lastName": "Bolton",
    "email": "troy@gmail.com",
    "password": "Troy1022"
}

###
DELETE  http://localhost:3000/users/633cea619475ad3f03ca2091

// PRODUCTION Deploy 
###
GET https://cse341-project-b0xp.onrender.com/users
###
GET https://cse341-project-b0xp.onrender.com/users/633bb262efc8b83678a89893
###
POST  https://cse341-project-b0xp.onrender.com/users HTTP/1.1
Content-Type: application/json

{
    "firstName": "Cooper",
    "lastName": "Kupp",
    "email": "kupp@gmail.com",
    "password": "Kupp10copper"
}
###
PUT  https://cse341-project-b0xp.onrender.com/users/633cbb845e592efcab15889b
Content-Type: application/json

{
    "firstName": "Trayce",
    "lastName": "Bolton",
    "email": "trey@gmail.com",
    "password": "Troy1022"
}

###
DELETE  https://cse341-project-b0xp.onrender.com/users/633cf05591d8456387b3183e

